-- Start of user code DB Name
-- TODO specify the name of database used
USE dsl.entity.gen.java.dao.tests;
-- End of user code

-- Tables for Entity Entity 1 

DROP TABLE IF EXISTS ENTITY1;
CREATE TABLE ENTITY1
(
	ID CHAR(32) NOT NULL,
	ATTRIBUTE1 INT(1) ,
	ATTTRIBUTE2 DATETIME ,
	ATTTRIBUTE3  ,
	ATTTRIBUTE4 VARCHAR(255) ,
	ATTTRIBUTE5 DOUBLE ,
	ATTTRIBUTE6 INT ,
	ATTTRIBUTE7 VARCHAR(255) ,
	PRIMARY KEY (ID)
);

-- Tables for Entity Entity4 

DROP TABLE IF EXISTS ENTITY4;
CREATE TABLE ENTITY4
(
	-- 1-->|*|
	FK_ENTITY6_REFERENCE4_ID CHAR(32),
	FK_INHERITS_ENTITY1_ID CHAR(32) NOT NULL,
	PRIMARY KEY (FK_INHERITS_ENTITY1_ID)
);

-- Tables for Entity Entity6 

DROP TABLE IF EXISTS ENTITY6;
CREATE TABLE ENTITY6
(
	ID CHAR(32) NOT NULL,
	-- 1-->|*|
	FK_ENTITY4_REFERENCE3_ID CHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);

-- Tables for Entity Entity7 

DROP TABLE IF EXISTS ENTITY7;
CREATE TABLE ENTITY7
(
	ID CHAR(32) NOT NULL,
	-- |*|-->1
	FK_ENTITY8_REFERENCE5_ID CHAR(32),
	PRIMARY KEY (ID)
);

-- Tables for Entity Entity8 

DROP TABLE IF EXISTS ENTITY8;
CREATE TABLE ENTITY8
(
	ID CHAR(32) NOT NULL,
	-- |1|<-->1
	FK_ENTITY7_REFERENCE6_ID CHAR(32) UNIQUE,
	PRIMARY KEY (ID)
);

-- Tables for Entity Entity2 

DROP TABLE IF EXISTS ENTITY2;
CREATE TABLE ENTITY2
(
	ID CHAR(32) NOT NULL,
	ATTRIBUTE8 VARCHAR(255) ,
	-- |*|-->1
	FK_ENTITY3_REFERENCE1_ID CHAR(32),
	PRIMARY KEY (ID)
);

-- Tables for Entity Entity3 

DROP TABLE IF EXISTS ENTITY3;
CREATE TABLE ENTITY3
(
	ID CHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);

-- Tables for Entity Entity5 

DROP TABLE IF EXISTS ENTITY5;
CREATE TABLE ENTITY5
(
	-- |*|-->1
	FK_ENTITY6_REFERENCE2_ID CHAR(32),
	-- |*|-->1
	FK_ENTITY3_REFERENCE1_ID CHAR(32),
	FK_INHERITS_ENTITY2_ID CHAR(32) NOT NULL,
	PRIMARY KEY (FK_INHERITS_ENTITY2_ID)
);

