-- Start of user code DB Name
-- TODO specify the name of database used
USE sample;
-- End of user code

-- Tables for Entity Basic 

DROP TABLE IF EXISTS BASIC;
CREATE TABLE BASIC
(
	MY_PROP1 VARCHAR(255) NOT NULL,
	MY_PROP2 DOUBLE NOT NULL,
	FK_INHERITS_ROOT_ID CHAR(32) NOT NULL,
	PRIMARY KEY (FK_INHERITS_ROOT_ID)
);

-- Tables for Entity BasicWithoutAttr 

DROP TABLE IF EXISTS BASIC_WITHOUT_ATTR;
CREATE TABLE BASIC_WITHOUT_ATTR
(
	FK_INHERITS_ROOT_ID CHAR(32) NOT NULL,
	PRIMARY KEY (FK_INHERITS_ROOT_ID)
);

-- Tables for Entity Root 

DROP TABLE IF EXISTS ROOT;
CREATE TABLE ROOT
(
	ID CHAR(32) NOT NULL,
	ROOT_PROP  NOT NULL,
	PRIMARY KEY (ID)
);

-- Tables for Entity ClassA1 

DROP TABLE IF EXISTS CLASS_A1;
CREATE TABLE CLASS_A1
(
	ID CHAR(32) NOT NULL,
	A1 DOUBLE NOT NULL,
	PRIMARY KEY (ID)
);

-- Tables for Entity ClassA2 

DROP TABLE IF EXISTS CLASS_A2;
CREATE TABLE CLASS_A2
(
	A2 VARCHAR(255) NOT NULL,
	FK_INHERITS_CLASS_A1_ID CHAR(32) NOT NULL,
	PRIMARY KEY (FK_INHERITS_CLASS_A1_ID)
);

-- Tables for Entity ClassA3 

DROP TABLE IF EXISTS CLASS_A3;
CREATE TABLE CLASS_A3
(
	A3 VARCHAR(255) NOT NULL,
	FK_INHERITS_CLASS_A2_ID CHAR(32) NOT NULL,
	PRIMARY KEY (FK_INHERITS_CLASS_A2_ID)
);

-- Tables for Entity Main 

DROP TABLE IF EXISTS MAIN;
CREATE TABLE MAIN
(
	ID CHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);

-- Tables for Entity Sub1 

DROP TABLE IF EXISTS SUB1;
CREATE TABLE SUB1
(
	FK_INHERITS_MAIN_ID CHAR(32) NOT NULL,
	PRIMARY KEY (FK_INHERITS_MAIN_ID)
);

-- Tables for Entity Sub2 

DROP TABLE IF EXISTS SUB2;
CREATE TABLE SUB2
(
	FK_INHERITS_MAIN_ID CHAR(32) NOT NULL,
	PRIMARY KEY (FK_INHERITS_MAIN_ID)
);

