<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graalextensions"
    nsURI="http://mindef.gouv.fr/dsl/safran/graal-extensions/1.0.0" nsPrefix="sge">
  <eClassifiers xsi:type="ecore:EClass" name="Risk" eSuperTypes="platform:/plugin/org.obeonetwork.dsl.environment/model/environment.ecore#//MetaData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benefits" eType="#//BenefitsLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="drawbacks" eType="#//DrawbacksLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="risk" eType="#//RiskLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BenefitsLevel">
    <eLiterals name="undefined" literal="undefined"/>
    <eLiterals name="_1" value="1" literal="1"/>
    <eLiterals name="_2" value="2" literal="2"/>
    <eLiterals name="_3" value="3" literal="3"/>
    <eLiterals name="_4" value="4" literal="4"/>
    <eLiterals name="_5" value="5" literal="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DrawbacksLevel">
    <eLiterals name="undefined" literal="undefined"/>
    <eLiterals name="_1" value="1" literal="1"/>
    <eLiterals name="_2" value="2" literal="2"/>
    <eLiterals name="_3" value="3" literal="3"/>
    <eLiterals name="_4" value="4" literal="4"/>
    <eLiterals name="_5" value="5" literal="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RiskLevel">
    <eLiterals name="undefined" literal="undefined"/>
    <eLiterals name="_1" value="1" literal="1"/>
    <eLiterals name="_2" value="2" literal="2"/>
    <eLiterals name="_3" value="3" literal="3"/>
    <eLiterals name="_4" value="4" literal="4"/>
    <eLiterals name="_5" value="5" literal="5"/>
  </eClassifiers>
</ecore:EPackage>
