<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="soa" nsURI="http://www.obeonetwork.org/dsl/soa/3.0.0" nsPrefix="soa">
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="../../org.obeonetwork.dsl.environment/model/environment.ecore#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponents" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedWires" upperBound="-1"
        eType="#//Wire" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="../../org.obeonetwork.dsl.environment/model/environment.ecore#//ObeoDSMObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedServices" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredServices" upperBound="-1"
        eType="#//Service" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedServices" upperBound="-1"
        eType="#//Service" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementations" upperBound="-1"
        eType="#//ImplementationComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBinding" upperBound="-1"
        eType="#//Binding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" upperBound="-1"
        eType="ecore:EClass ../../org.obeonetwork.dsl.environment/model/environment.ecore#//TypesDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apiVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deprecated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="../../org.obeonetwork.dsl.environment/model/environment.ecore#//ObeoDSMObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInterface" eType="#//Interface"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronization" lowerBound="1"
        eType="#//SynchronizationKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//InterfaceKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedInterface" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" eType="#//Binding"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedTypes" upperBound="-1"
        eType="ecore:EClass ../../org.obeonetwork.dsl.environment/model/environment.ecore#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wire" eSuperTypes="../../org.obeonetwork.dsl.environment/model/environment.ecore#//ObeoDSMObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dest" eType="#//Service"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="../../org.obeonetwork.dsl.environment/model/environment.ecore#//ObeoDSMObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="technology" eType="#//BindingKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="../../org.obeonetwork.dsl.environment/model/environment.ecore#//ObeoDSMObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperations" upperBound="-1"
        eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InterfaceKind">
    <eLiterals name="provided"/>
    <eLiterals name="required" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SynchronizationKind">
    <eLiterals name="synchronous" literal="synchronous"/>
    <eLiterals name="asynchronous" value="1" literal="asynchronous"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="../../org.obeonetwork.dsl.environment/model/environment.ecore#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//OperationKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="public" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fault" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verb" eType="#//Verb" defaultValueLiteral="GET"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exposition" eType="#//ExpositionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementationComponent" eSuperTypes="../../org.obeonetwork.dsl.environment/model/environment.ecore#//ObeoDSMObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implement" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" eType="ecore:EClass ../../org.obeonetwork.dsl.environment/model/environment.ecore#//TypesDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="../../org.obeonetwork.dsl.environment/model/environment.ecore#//ObeoDSMObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../org.obeonetwork.dsl.environment/model/environment.ecore#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="ecore:EEnum ../../org.obeonetwork.dsl.environment/model/environment.ecore#//MultiplicityKind"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passingMode" eType="#//ParameterPassingMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BindingKind">
    <eLiterals name="webservice"/>
    <eLiterals name="rmi" value="1"/>
    <eLiterals name="corba" value="2"/>
    <eLiterals name="ejb" value="3"/>
    <eLiterals name="java" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationKind">
    <eLiterals name="REQUEST_RESPONSE"/>
    <eLiterals name="ONE_WAY" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Verb">
    <eLiterals name="GET"/>
    <eLiterals name="POST" value="1"/>
    <eLiterals name="PUT" value="2"/>
    <eLiterals name="DELETE" value="3"/>
    <eLiterals name="HEAD" value="4"/>
    <eLiterals name="OPTIONS" value="5"/>
    <eLiterals name="PATCH" value="6"/>
    <eLiterals name="TRACE" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterPassingMode">
    <eLiterals name="BODY"/>
    <eLiterals name="PATH" value="1"/>
    <eLiterals name="QUERY" value="2"/>
    <eLiterals name="COOKIE" value="3"/>
    <eLiterals name="HEADER" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExpositionKind">
    <eLiterals name="NONE"/>
    <eLiterals name="REST" value="1"/>
    <eLiterals name="SOAP" value="2"/>
  </eClassifiers>
</ecore:EPackage>
