CREATE SEQUENCE AW_PERSONNE_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE -1 START WITH 1000 NOCYCLE;

CREATE SEQUENCE AW_ADRESSE_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE -1 START WITH 1000 NOCYCLE;

CREATE SEQUENCE AW_COMPETENCE_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE -1 START WITH 1000 NOCYCLE;

CREATE SEQUENCE AW_COMPETENCE_PERSO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE -1 START WITH 1000 NOCYCLE;

CREATE SEQUENCE AW_PERSONNE_N_COMPETENCE_P_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE -1 START WITH 1000 NOCYCLE;

CREATE SEQUENCE AW_TELEPHONE_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE -1 START WITH 1000 NOCYCLE;

CREATE SEQUENCE AW_MAIL_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE -1 START WITH 1000 NOCYCLE;

CREATE SEQUENCE AW_UTILISATEUR_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE -1 START WITH 1000 NOCYCLE;

CREATE SEQUENCE AW_ROLE_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE -1 START WITH 1000 NOCYCLE;

CREATE SEQUENCE AW_PERMISSION_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE -1 START WITH 1000 NOCYCLE;

