-- ==============================================================
--  Table : EMPLOYEES                                    
-- ==============================================================
DROP PUBLIC SYNONYM EMPLOYEES;

DROP TABLE EMPLOYEES;
CREATE TABLE EMPLOYEES(
    EMPLOYEEID NUMBER(22,) NOT NULL,
    REPORTSTO NUMBER(22,) NULL,
    POSTALCODE VARCHAR2(10) NULL,
    LASTNAME VARCHAR2(20) NOT NULL,
    NOTES CLOB NULL,
    TITLE VARCHAR2(30) NULL,
    REGION VARCHAR2(15) NULL,
    FIRSTNAME VARCHAR2(10) NOT NULL,
    ADDRESS VARCHAR2(60) NULL,
    HIREDATE DATE NULL,
    PHOTOPATH VARCHAR2(255) NULL,
    BIRTHDATE DATE NULL,
    TITLEOFCOURTESY VARCHAR2(25) NULL,
    HOMEPHONE VARCHAR2(24) NULL,
    COUNTRY VARCHAR2(15) NULL,
    CITY VARCHAR2(15) NULL,
    EXTENSION VARCHAR2(4) NULL,
    PHOTO BLOB NULL
)
;

CREATE PUBLIC SYNONYM EMPLOYEES FOR NORTHWIND.EMPLOYEES;

